### ISSUE TITLE
Bootstrap iso doesn't work when booted from USB drive

### ISSUE THREAD

**Issue by agracey** [rancher/elemental-cli#284]
It looks like the new stack only works when booted from a cd drive. This works for VMs but fails when using my NUCs.

From some digging, it looks like this might be an issue with the [cdrom provider](https://github.com/davidcassany/linuxkit/blob/73e2e3a171a00edb9e63d4805ba46704a8c29208/pkg/metadata/providers/provider_cdrom.go#L19) only looking for disks with certain device names or labels. 

I tried adding a label with `elemental build-iso [...] --label cidata` but this image won't even boot fully :(

**Comment by agracey** [comment]
I think I found a possible workaround by manually copying over the right file from the iso in `01_ros-rootfs.yaml`:

```
  network:
>    - if: '[ ! -f /oem/userdata.yaml ]'
>      commands:
>      - cp /run/initramfs/live/config /oem/userdata.yaml
<    - if: '[ ! -f /oem/userdata]'
>    - if: '[ ! -f /oem/userdata.yaml ]'
      name: "Pull data from provider"
      datasource:
        providers: ["cdrom", "gcp", "openstack", "aws", "azure", "hetzner", "packet", "scaleway", "vultr", "digitalocean", "metaldata" ]
        path: "/oem"
      files:
      - path: /oem/userdata_load
<    - if: '[ -f /oem/userdata] && [ -f /oem/userdata_load ]'
>    - if: '[ -f /oem/userdata.yaml ] && [ -f /oem/userdata_load ]'
      commands:
<      - elemental cloud-init -s initramfs /oem/userdata
<      - elemental cloud-init -s boot /oem/userdata
>      - elemental cloud-init -s initramfs /oem/userdata.yaml
>      - elemental cloud-init -s boot /oem/userdata.yaml
      - rm -rf /oem/userdata_load
```

**Comment by Itxaka** [comment]
This is weird. AFAIK CIDATA label is only to provide a cdrom WITH cloud-config data. Like is the only thing provided in that cdrom, so you can boot with no cloud sources, i.e. you boot from cd/usb and have a different CD with the cloud-config on it, with the cidata label. We even use that on our testing (https://github.com/rancher/elemental-toolkit/blob/ee69c3696ab7403fe58fe39e71e6205a86cb073c/make/Makefile.test#L148) so this should not have anything to do with the cdrom.

Your patch seems to suggest that the problem is that we save the file with a different format (userdata vs userdata.yaml) which I have no idea where that comes from....

**Comment by davidcassany** [comment]
Indeed a CDROM device to be used as a cdrom provider for the cloud init data needs to match the cloud-init expectations from `cloud-init` project. This logics comes from linuxkit project which follow `cloud-init` expectations, the logic is here https://github.com/davidcassany/linuxkit/blob/73e2e3a171a00edb9e63d4805ba46704a8c29208/pkg/metadata/providers/provider_cdrom.go#L58-L61

So the device needs to be listed under `/dev/*`, be formatted with fat32 or iso9660 and labeled as `CIDATA` or `cidata`. Then from the root of a matched device it reads the `/user-data` file or `/config` (as a fallback).

> I tried adding a label with elemental build-iso [...] --label cidata but this image won't even boot fully :(

Yes this won't boot since the label is coupled with the grub configuration, hence using a custom label requires a custom grub configuration, the label is part of the kernel [parameters for booting](https://github.com/rancher/elemental-toolkit/blob/1f25bc0dc80e38b93ca6cefc2dc010e0ba64dd68/packages/livecd/grub2/config/grub_live.cfg#L24).

I believe there is some confusion around the `/oem/userdata` file because `elemental-operator register` command is writing it's own `/oem/userdata` [file](https://github.com/rancher/elemental-operator/blob/2381ebc55a0e00fcf6e7ed0604accaf10559e8b3/cmd/operator/register/root.go#L172-L186) and the `datasource` yip plugin also writes its own `/oem/userdata` [file](https://github.com/mudler/yip/blob/30d215fa4ab014413d10267be8b9c599d9da28ef/pkg/plugins/datasource.go#L151-L161)... 🤔 

So IMHO there are few connected issues here:

* Proper use of cdrom userdata provider, it is expected that userdata from a CDROM (or any applicable device) is not the same device as the live ISO.
* elemental-operator and datasource yip plugin both write a `/oem/userdata` file, this is bad, it can easily lead to weird behaviors like having different content in this file depending on the booting stage... IMHO this is a bug!
* why elemental-operator is even writing the `/oem/userdata` file? Do we expect `elemental-operator register` to provide any cloud-init data beyond the cloud-init data required for the installation? or in different words, do we expect `elemental-operator register` command to provide cloud-init even when called from an already installed node? This is somehow related to rancher/elemental-operator#52, cloud-init data management in `elemental-operator` still requires some love.

**Comment by Itxaka** [comment]
> why elemental-operator is even writing the /oem/userdata file?

Doesn't that may come from the ros-installer? IIRC it used to pick the cloud-config FROM /oem/userdata so it makes sense that we saved the registrationurl cloud-config into /oem/userdata if we were expected to call ros-installer afterwards with that userdata. We now need to call elemental with that cloud-init file, but we could choose any other name. After all, we want that cloud-config file to end up in the final installation, so it makes sense to pass ti to the installer so it can copy it into the final /oem system.

> Proper use of cdrom userdata provider, it is expected that userdata from a CDROM (or any applicable device) is not the same device as the live ISO.

I think that works as expected, as yip also checks under `/sys/class/block/*` which is where Im guessing a SCSI cdrom should appear. Easily testable via a VM with a SCSI cdrom.

**Comment by agracey** [comment]
> I think that works as expected, as yip also checks under /sys/class/block/* which is where Im guessing a SCSI cdrom should appear. Easily testable via a VM with a SCSI cdrom.

Would a scsi cdrom show up the same as a USB drive?

**Comment by Itxaka** [comment]
It should, they all are under block devices. The lib just filters by FS (FAT32 or iso9660) and label (cidata).

But that is meant as a nocloud source, i.e. a bare metal in which the cloud init files are provided via a cd(different from the boot drive) or a usb (again different that the boot drive)

**Comment by agracey** [comment]
But if the USB drive is the boot drive? There should be some way to treat them the same, right?

**Comment by Itxaka** [comment]
Mmh, I guess that if your user data is on the root of the disk and you label the device cidata and modify grub to search for that label, sure it can be done. 

But there are easier methods. You can build an ISO with the cloud config embedded, or have an extra usb with that data. Or pass it via cmdline on grub booting.

**Comment by agracey** [comment]
The config does get put at the root of the iso already. Just to make sure there's no mis-communication. This config is the registration yaml that gets curled from the MachineRegistration endpoint. 

Having an extra usb is a no-go but passing it through the grub command line, we could likely make that work. What's the variable that needs to be set?

**Comment by kkaempf** [comment]
I can recreate the problem with an old laptop by
- copy an ISO image to a USB stick
- boot the laptop from this USB stick
- `/oem` only contains `userdata_load`
- elemental-operator stops immediately after startup with (succeeded), but didn't do anything

Looking at `/proc/partitions`, the USB stack appears as `/dev/sda`

**Comment by kkaempf** [comment]
The config is available at `/run/initramfs/live/config`
Copying it to `/oem/userdata` and restarting elemental-operator doesn't change a thing, though.

**Comment by agracey** [comment]
Try copying it to /oem/userdata.yaml and then try?

**Comment by agracey** [comment]
I don't understand the linkage and why it ever works but the patch I suggested above seems to?

**Comment by kkaempf** [comment]
> Try copying it to /oem/userdata.yaml and then try?

:+1: then `elemental-operator` starts to do something.

**Comment by davidcassany** [comment]
`elemental-operator` reads `*.yaml` files from the folder given as command line argument (in this case `/oem`, even it also defaults to `/oem` if no arguments are given).

I don't see the need of using the datasource concept form the same iso we are booting from, specially if we already provide some embedded data into the `/oem` squashed rootfs, so why not including some further data in `/system/oem` and it will be simply part of the installation. There is no need to make use of `datasource` cloud-init plugin, this was meant to be used for public cloud, `cdrom` and `file` data sources are more a testing and debugging utility than anything else.

Additional local cloud-init files are about to be possible as soon as I end with rancher/elemental-operator#52 then it will be possible to point cloud-init files (local or remote) within the machine registration spec. I am on my way to run few local tests and do the appropriate PRs.

**Comment by kkaempf** [comment]
> I don't see the need of using the datasource concept form the same iso we are booting from, specially if we already provide some embedded data into the `/oem` squashed rootfs

It's _not_ there when booting from USB stick. There's no useable data for elemental-operator in /oem.

> `cdrom` and `file` data sources are more a testing and debugging utility than anything else.

Booting from (real or simulated) CD-ROM or a USB Stick will be normal for edge deployments. Esp. the latter, when the boot media doesn't appear as /dev/srX, does not work.

> 
> Additional local cloud-init files are about to be possible as soon as I end with [rancher/elemental-operator#52](https://github.com/rancher/elemental-operator/issues/52) then it will be possible to point cloud-init files (local or remote) within the machine registration spec. I am on my way to run few local tests and do the appropriate PRs.

:eyes:

**Comment by agracey** [comment]
It looks like elemental-operator can accept multiple directories (I think I'm reading the code right?). Would it make sense to pass both `/oem` and `/run/initramfs/live/` as directories to look in? Then we can rename config to config.yaml and it would see it, right?

Another thing that I noticed is that the config doesn't stay in /oem on disk so future reboots don't see it. It would be useful to keep it persistent since it allows us to reprovision later on.

**Comment by kkaempf** [comment]
> 
> Another thing that I noticed is that the config doesn't stay in /oem on disk so future reboots don't see it.

This is the correct behavior imho.
There are two cloud-configs
1. the one used when booting from ISO, its main purpose is to ensure network connection to Rancher Manager (besides other flags)
2. the one pulled from Rancher Manager when `elemental-operator` starts up, this defines the device etc.

These are two different cloud-configs (one embedded/frozen in the ISO, one dynamically pulled and changeable).
We're only talking about the first one here. And both shouldn't be mixed (imho).

**Comment by davidcassany** [comment]
> It looks like elemental-operator can accept multiple directories (I think I'm reading the code right?).

Yes, this is also my understanding, even I have not actually tested it to be honest. My understanding is that it takes multiple directories and it reads any *.yaml file from these directories.

> Would it make sense to pass both /oem and /run/initramfs/live/ as directories to look in? Then we can rename config to config.yaml and it would see it, right?

I am not sure what your `config` is and how it gets there, but if this is the registration data downloaded from the registration URL of the machine registration CRD it makes sense.

> Another thing that I noticed is that the config doesn't stay in /oem on disk so future reboots don't see it. It would be useful to keep it persistent since it allows us to reprovision later on.

There is no design in place for that, at least that I am aware of. A convoluted way of achieving it could by passing this file as a `config-url` with the machine registration spec as in the example from https://github.com/rancher/elemental-operator/pull/61#issuecomment-1189293294

**Comment by agracey** [comment]
> These are two different cloud-configs (one embedded/frozen in the ISO, one dynamically pulled and changeable).
> We're only talking about the first one here. And both shouldn't be mixed (imho).

Fair, does the "frozen in time" config get saved in the recovery partition to use?

>I am not sure what your config is and how it gets there, but if this is the registration data downloaded from the registration URL of the machine registration CRD it makes sense.

That file is included by the iso build script so we can change the name easily

**Comment by Itxaka** [comment]
I think we are talking about different cloud init configs here?

 1 - The one injected on the iso that can have for example a registrationURL embedded
 2 - The one obtained from running the datasources (i.e. as part of any service that calls yip/elemental run-stage)
 3 - The one obtained from the registrationURL as part of running elemental-operator


1 is valid if we want to have an autoinstaller, i.e. you create your iso with a cloud-config that has a RegistrationURL and a install.automatic=true and that will get stored (for some weird reason???) into `/config` (???)
2 will come from the `01_elemental-rootfs.yaml` and should get stored as `/etc/userdata` if found in any of the sources.
3 will only come after running the `elemental-operator register`. This should not be storing the file locally anymore after @davidcassany patches, althougth it may come over if there are new PRs as I know this is moving around currently-



So 1 is the one wee should be interested on. 


> That file is included by the iso build script so we can change the name easily

Which one? There is like 4 around already lol.

> Fair, does the "frozen in time" config get saved in the recovery partition to use?

Probably not. Especially in the elemental context. If you boot from an iso and use the elemental-cli to install we have an option to pass a cloud-config and that gets installed in the new system, but on the context of elemental...you will be using a cloud-config for your machine given out via the registrationURL, so the cloud config injected in to the ISO should only be valid for as long as you are in the ISO, not for the install. See it as a step. Step 1 is getting elemental ISO to contact Rancher and get its configuration, thats what the cloud-init injected is for. The rest of the steps is for the Rancher config to produce.

**Comment by davidcassany** [comment]
> Fair, does the "frozen in time" config get saved in the recovery partition to use?

No, or not explicitly at least. However I don't see any further use of this file other than running an installation and the installation can only be done from an installation media. The recovery should be used only to take back the very first installation of the immutable rootfs while all persistent files (including system agent config and all other cloud-init files) should still be there.

The current setup considers only running `elemental-operator register` from the installation media. If we consider running on every boot `elementa-operator register` we need to understand what's the motivation first, with the current implementation if `elemental-operator register` is executed from the already installed host it should do the authentication procedure and fetch the config, however it will not write any cloud-init file neither run any installation, hence on changes on client side.

**Comment by Itxaka** [comment]
ok, `/oem/userdata_load` appears in there because on https://github.com/rancher/elemental/blob/master/framework/files/system/oem/01_elemental-rootfs.yaml if there isnt a `/oem/userdata` it tries to get the datasources and output it to `/oem/userdata_load` and then if there is a `/oem/userdata_load` it runs elemental with it, which makes sense.

If there are no sources, it still puts the userdata_load in there so thats why that file is always appearing. Also the check that deletes that file afterwars will not work unless there was real sources, so the file is left there forever. Fixing that its easy.

Also, the config being injected (Lets call it livecd-cloud-config?) is put under `/run/inintramfs/live/config` which means that any injected file is currently not working.

https://github.com/rancher/elemental/blob/master/framework/files/system/oem/01_elemental-rootfs.yaml should be modified so it checks for that file only on liveCD and runs it if needed. Although if we are expecting that file to be used by the operator, then we should not touch it? is the operator starting on boot? Does it pick that file?


I think its clear that we dont have a proper use-case for elemental with clear steps, i.e. `I want to build an iso image that on booting connects to a registrationurl and autoinstalls, with an extra cloud-config to be run on machine reboot`
We seems to be supporting 32 different ways of doing the same thing here and there, in different places for differents tweaks of the same thing, instead of having just one use case and focusing on that.

**Comment by Itxaka** [comment]
Seems clear to me, elemental was supposed to be run with the `ros-installer --config /run/initramfs/live/config` and its equivalent on the `elemental-operator` but we have now lose that possibility due to the changes in the elemental-operator, as it no long supports the install command directly nor it accepts a config file if Im not mistaken @davidcassany ?

So Im wondering...we should probably restore the config loading from file on the register so we can do:

![image](https://user-images.githubusercontent.com/1447686/179842800-e00fc98d-5084-4951-bbb0-1749ed19d213.png)


AFAIK this should require minimal changes to the config loading on the operator and a very small change to Elemental to run the operator. We can even run the operator register as a one off command via the /system/oem/ cloud config files so its fully automated and only done if the config file is provided

**Comment by davidcassany** [comment]
> we have now lose that possibility due to the changes in the elemental-operator, as it no long supports the install command directly nor it accepts a config file if Im not mistaken @davidcassany ?

it is not that we lost it, it is just slightly different. There is no `--config <path to file>` flag in `elemental-operator register`, but it accepts arguments, these arguments are expected to be folder paths and any `*.yaml` file in these folders gets loaded. So, as @agracey noted, running `elemental-operator register /run/initramfs/live` would do the trick if the `config` file is named `config.yaml`.

> AFAIK this should require minimal changes to the config loading on the operator and a very small change to Elemental to run the operator.

Yes, indeed, only changing the `elemental-operator register` call arguments to include `/run/initramfs/live` and rename the embedded `config` file into `config.yaml`.

> We can even run the operator register as a one off command via the /system/oem/ cloud config files so its fully automated and only done if the config file is provided

Yes, I also think this is a nice idea, there is a card to call `elemental-operator` as part of the `/system/oem` configs rancher/elemental-operator#62

**Comment by kkaempf** [comment]
Then we need two changes here, right ?
1. Change the `elemental-operator.service` file to 
```
ExecStart=/usr/sbin/elemental-operator register /run/initramfs/live
```
2. Change the `elemental-iso-build` script to create `config.yaml` instead of `config`

🤔

**Comment by kkaempf** [comment]
For `elemental-iso-build`:
```
diff --git a/elemental-iso-build b/elemental-iso-build
index fa90690..6c43dec 100755
--- a/elemental-iso-build
+++ b/elemental-iso-build
@@ -14,7 +14,7 @@ build() {
   curl https://raw.githubusercontent.com/rancher/elemental/master/iso/grub.cfg -fsSL -o "$TEMPDIR"/iso/grub.cfg
   # Did we copy the custom cloud config? Then no need to download the default one
   if [[ -z "$CLOUD_CONFIG_FILE" ]]; then
-    curl https://raw.githubusercontent.com/rancher/elemental/master/iso/config -fsSL -o "$TEMPDIR"/iso/config
+    curl https://raw.githubusercontent.com/rancher/elemental/master/iso/config -fsSL -o "$TEMPDIR"/iso/config.yaml
   fi
 
   pushd "$TEMPDIR" || exit 1
```

**Comment by Itxaka** [comment]
@kkaempf kind of yeah. I called the file `livecd-cloud-config.yaml` in my branch so its more clear, will update the script as part of it

Also I dropped the service and instead have an extra cloud-config on elemental:

99_elemental-operator.yaml

```
name: "Elemental operator bootstrap"
stages:
  network:
    # run only if on live cd and there is a config file
    - if: '[ -f /run/cos/live_mode ] && [ -f /run/initramfs/live/livecd-cloud-config.yaml ]'
      commands:
        - elemental-operator register --debug /run/initramfs/live/
```

**Comment by kkaempf** [comment]
> @kkaempf kind of yeah. I called the file `livecd-cloud-config.yaml` in my branch so its more clear, will update the script as part of it

Confirmed working.
