### ISSUE TITLE
If more than one partition has a COS_* label, upgrade wont work

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-cli#348]
Reported to harvester folks: https://github.com/harvester/harvester/issues/3070

FC storage without multipath, so the disk is seen 4 times.

This seems to confuse elemental-cli as it will just try to mount the fist found partition for COS_STATE. We should make sure that we mount the ACTIVE COS_STATE (On upgrade it should be mounted RO and we remount it RW)

Patch that fixes it: https://github.com/Vicente-Cheng/elemental-cli/commit/5ccfbbc22f3870ab667408a9377af1649f770f8d

This patch could be backported to an older version to unblock the harvester upgrade path.

Harvester is using v0.0.14+gedc412

**Comment by Vicente-Cheng** [comment]
> Reported to harvester folks: [harvester/harvester#3070](https://github.com/harvester/harvester/issues/3070)
> 
> FC storage without multipath, so the disk is seen 4 times.
> 
> This seems to confuse elemental-cli as it will just try to mount the fist found partition for COS_STATE. We should make sure that we mount the ACTIVE COS_STATE (On upgrade it should be mounted RO and we remount it RW)
> 
> Patch that fixes it: [Vicente-Cheng@5ccfbbc](https://github.com/Vicente-Cheng/elemental-cli/commit/5ccfbbc22f3870ab667408a9377af1649f770f8d)
> 
> This patch could be backported to an older version to unblock the harvester upgrade path.
> 
> Harvester is using v0.0.14+gedc412

update the more clear patch here [Vicente-Cheng@42611f5](https://github.com/Vicente-Cheng/elemental-cli/commit/42611f566b031e39e82cc1109611279c89884307)

thanks!

**Comment by Itxaka** [comment]
PR to specific branch for harvester here: https://github.com/rancher/elemental-cli/pull/350

As harvester uses luet for bringing the packages, we will also need to create an specific branch on cos-toolkit and bump elemental-cli in that branch so it gets pushed to the repos.

They are using 20220420151313-repository.yaml which sucks because its before we used the commit id to identify the repos :/

Looking to match the exact commit to that repository.yaml file

Extra info: using the green repo.

**Comment by Itxaka** [comment]
We are lucky, the package meta indicates that this was built on 17/04/2022 so there is only one push that day. The commit sha linked to harvester repository is https://github.com/rancher/elemental-toolkit/commit/c18d8d9bdb4646c00893c84eec616eb2465c1020

**Comment by Itxaka** [comment]
https://github.com/rancher/elemental-toolkit/tree/v0.8.9-11-harvester1 is the branch that supports the elemental-cli branch with he fix

We should probably also rework the workflows to publish on main AND that extra branch as part of the branch, otherwise  it wont be published

**Comment by Itxaka** [comment]
This also happens on latest! I thougth we may be using the state.yaml to identify the original partition where we installed stuff (by UUID or something) but we do not. Something to add maybe?

**Comment by davidcassany** [comment]
To me this unveils there could be corner cases where identifying partitions by default labels or partitions is not reliable enough. In fact there are cases in which it could actually make sense including more than one disk with valid Elemental layouts as @bk201 pointed out in https://github.com/rancher/elemental-cli/pull/350#issuecomment-1299969243. 

So I believe there two different but closely related scenarios where we fail:
1. Multiple disks including elemental installations
2. Same physical device represented by multiple devices in udev database

**For issue 1:**
A possible fix for this could be making all labels configurable at install time. Which is currently not fully possible as the grub configuration is coupled with the layout (it includes label literals in its configuration). This would be a clean solution for the multiple disk including elemental partitions cases. This would require rancher/elemental-toolkit#1773, one of the motivations of this card was to decouple as much as possible the static grub.cfg provided by the image to the installed layout (aka provide the `rd.cos.oemlabel` according to the installation setup instead of hardcoding it). Probably we should assume grub always gets the label values from a variable (which could be set at install/reset time) instead of hardcoding it.

Another option, probably more robust, could be relaying on UUIDs instead of labels. However this would not be possible for MSDOS partition tables we also support, probably time to deprecate (not drop) MSDOS support. If we relay on UUIDs we could set the UUID within the state yaml and keep a unique reference to partitions and find them by UUID as the first option, then fallback to label if missing and finally fallback to partition label.

**For issue 2:**
For these other weird cases where we have the same disk as different devices the state of both is not fully equivalent (mountpoints and such) I am not sure how to deal with it. I am wondering what happens if we mount persistent partition from device A but state partition from device B. This should be still ok right? So probably what we need is ensure calls to remounts and similar stuff are always pointing the right device. I believe the in those cases the logic belongs to places like https://github.com/rancher/elemental-cli/blob/29bbdc21d6d9bd6dac133458939a7835db4ee89c/pkg/types/v1/config.go#L330-L354 My problem here is how actually distinguish the appropriate device. Which would be the criteria? Any idea? Probably enforce using the mounted device of the currently running system?

Finally another point that this issue raises it that it would be nice to load state yaml confing during upgrades to get a better insight on the configuration. So probably all this can be somehow split in three different issues. @Itxaka do you have other ideas around this ? I see proper fixes require quite some work, probably we should brainstorm around it.

**Comment by kkaempf** [comment]
:+1: on sunsetting DOS partition tables

**Comment by Itxaka** [comment]
on the issue 2 (which I think its the one to tackle, more on this later) I guess it depends on the boot path.

If active/passive -> Mount whatever is mounted already, i.e. what has a mountpoint as that its the one being used and that we are able to remount RW.
if recover -> Mount whichever, we should really not care.

There is no other way we can work around this unless multipath is enabled and we use the md device no? To the system, both "disks" are different but they actually will have the same values everywhere, including UUIDs.

I mean, we could store the device in the state.yaml and use that to identify the "original" path for a given partition but...Im havent used FC storage, what happens if you install on /dev/sda but the system thinks you booted from /dev/sdb? Is that even possible?


On issue 1 -> I would disregard that. Not supported. Otherwise the whole cli has to change to support this. Is this something that any sane person is gonna do? Install elemental-based systems into several disks on the same server? Doesnt seems to me like a use-case, nor anything we have supports that use-case. I would mark it as non-supported and thats that.

**Comment by davidcassany** [comment]
> on the issue 2 (which I think its the one to tackle, more on this later) I guess it depends on the boot path.

I agree this is the _urgent_ one to tackle as if it raises there won't be easy workarounds. We should think how to gate that into a single place. Gonna check if there are other parts beyond the code I already pointed.

> On issue 1 -> I would disregard that. Not supported. Otherwise the whole cli has to change to support this. Is this something that any sane person is gonna do? Install elemental-based systems into several disks on the same server? Doesnt seems to me like a use-case, nor anything we have supports that use-case. I would mark it as non-supported and thats that.

Well, it is not the whole cli has to change, elemental-toolkit should not relay on a hardcoded layout, we are not that far. We just need to get rid of label literals in elemental-toolkit (grub2 config and cloud-init OEM partition config). Also the use case reported by @bk201 if I got it right make sense to me. Imagine a harvester host deploying elemental teal nodes where VM disks are actual volumes/disks visible to the harvester host. In that case there could be a collision of labels.

**Comment by Itxaka** [comment]
> Imagine a harvester host deploying elemental teal nodes where VM disks are actual volumes/disks visible to the harvester host. In that case there could be a collision of labels.

I dunno, for that it would require raw disks to be passed to the VMs if Im understanding this, so the harvester hosts would have several directly attached disks and those would appear on the hosts when looking by label. BUT that gets fixed by the issue 2, if its not mounted, ignore it for the upgrade.

Recovery its another beast but I dont think harvester does the upgrades via recovery, nor anything else (You can do the upgrade from active/passive, recovery should be to recover.

Seems to me a very minor case that will probably be fixed by the issue 2 fix as well, so I would ignore it for now.

**Comment by Itxaka** [comment]
Do we count this as fixed @davidcassany ? Patch is in and also patch provided to harvester, we could expand this further but it should be in a different card with no bug or high prio attached?

**Comment by davidcassany** [comment]
Yes I think this card can be closed, the bugfix is provided to harvester and we already fixed that on our main. I'd just close it
